# Generated by Django 4.0 on 2021-12-27 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mainkw_pubamounttotal_alter_newskw_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainkw',
            old_name='pubAmount',
            new_name='pubAmountMonth',
        ),
    ]
