# Generated by Django 4.0 on 2022-01-06 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_mainkw_sectionplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainkw',
            name='kwQuality',
            field=models.CharField(max_length=100),
        ),
    ]
