# Generated by Django 4.0 on 2022-01-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_mainkw_sectionplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainkw',
            name='pubAmountMonth',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
