# Generated by Django 4.0 on 2022-01-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_keywordhistory1'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='keywordhistory1',
            constraint=models.UniqueConstraint(fields=('id', 'keyword'), name='unique keyword_history'),
        ),
    ]
