# Generated by Django 4.0 on 2022-01-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_keywordhistory1_unique keyword_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordhistory1',
            name='user_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='keywordhistory1',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
