# Generated by Django 4.0 on 2022-01-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_keywordhistory1_user_id_alter_keywordhistory1_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='keywordhistory1',
            name='unique keyword_history',
        ),
        migrations.AddConstraint(
            model_name='keywordhistory1',
            constraint=models.UniqueConstraint(fields=('user_id', 'keyword'), name='unique keyword_history'),
        ),
    ]
