# Generated by Django 4.0 on 2022-01-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_keywordhistory1_unique keyword_history_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpandKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_keyword', models.CharField(blank=True, max_length=1000, null=True)),
                ('keyword', models.CharField(blank=True, max_length=1000, null=True)),
                ('searchPC', models.IntegerField(blank=True, null=True)),
                ('searchMOBILE', models.IntegerField(blank=True, null=True)),
                ('pubAmountTotal', models.IntegerField(blank=True, null=True)),
                ('kwQuality', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'expand_keyword',
            },
        ),
        migrations.AddConstraint(
            model_name='expandkeyword',
            constraint=models.UniqueConstraint(fields=('main_keyword', 'keyword'), name='unique expand_keyword'),
        ),
    ]
