# Generated by Django 4.0 on 2022-01-20 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_rename_pubamounttotal_keywordhistory1_pubamounttotalblog'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='newskw',
            name='unique newskw',
        ),
        migrations.AddConstraint(
            model_name='newskw',
            constraint=models.UniqueConstraint(fields=('title', 'link'), name='unique newskw'),
        ),
    ]
