# Generated by Django 4.0 on 2022-01-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_newskw_unique newskw_newskw_unique newskw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livekw',
            name='ranking',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
