# Generated by Django 4.0 on 2022-01-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_livekw_ranking'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='livekw',
            name='unique livekw',
        ),
        migrations.AlterField(
            model_name='livekw',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='livekw',
            constraint=models.UniqueConstraint(fields=('keyword',), name='unique livekw'),
        ),
    ]
