# Generated by Django 4.0 on 2022-01-23 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_livekw_unique livekw_alter_livekw_amount_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='livekw',
            name='unique livekw',
        ),
        migrations.RemoveConstraint(
            model_name='newskw',
            name='unique newskw',
        ),
        migrations.AddConstraint(
            model_name='livekw',
            constraint=models.UniqueConstraint(fields=('keyword', 'created_on'), name='unique livekw'),
        ),
        migrations.AddConstraint(
            model_name='newskw',
            constraint=models.UniqueConstraint(fields=('title', 'link', 'created_on'), name='unique newskw'),
        ),
    ]
