# Generated by Django 3.2.9 on 2022-01-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_newstagscollector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainkw',
            name='updated_on',
            field=models.DateField(auto_now_add=True, default='2022-01-27'),
            preserve_default=False,
        ),
    ]
